// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDziJWZOtY6guFU5-vf62ZMHxzLWOAr9qM',
    appId: '1:110397543877:android:a9405c5202e5d1287567ac',
    messagingSenderId: '110397543877',
    projectId: 'kaja-salat-5414a',
    databaseURL: 'https://kaja-salat-5414a-default-rtdb.firebaseio.com',
    storageBucket: 'kaja-salat-5414a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8JFYuoITGYRiZlxdysw6M0rsI7TLCU44',
    appId: '1:110397543877:ios:77f6a7b88756ef447567ac',
    messagingSenderId: '110397543877',
    projectId: 'kaja-salat-5414a',
    databaseURL: 'https://kaja-salat-5414a-default-rtdb.firebaseio.com',
    storageBucket: 'kaja-salat-5414a.appspot.com',
    androidClientId: '110397543877-2p6b5ctifcvj4enieglcmgr5852pcr7f.apps.googleusercontent.com',
    iosClientId: '110397543877-kph56bnsr3n2a4qbr9dre48eso6g04cv.apps.googleusercontent.com',
    iosBundleId: 'com.onewk.onework',
  );
}
